#!/usr/bin/env bash
# Transfers a file from the client to the server.
if [ $# -lt 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	echo "scp -o \"StrictHostKeyChecking=no\" -i $1 $3@$2:$4"
fi
