#!/usr/bin/env bash
# Create a custom 404 page

sudo apt-get -y update
sudo apt-get -y install nginx
echo 'Holberton School for the win!' | sudo tee /var/www/html/index.nginx-debian.html
var="\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "35i \ $var" /etc/nginx/sites-available/default
sudo touch /var/www/html/404.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
var2="\terror_page 404 /404.html;"
sudo sed -i "36i \ $var2" /etc/nginx/sites-available/default
var3="\n\tlocation = /404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}"
sudo sed -i "44i \ $var3" /etc/nginx/sites-available/default
sudo service nginx start
