#!/usr/bin/env bash
# Install and configure HAproxy to handle traffic to other servers

sudo apt-get -y update
sudo apt-get install haproxy=1.6.\*
var1="\nfrontend www.michellegsld.tech\n\tbind *:80\n\tmode http\n\tdefault_backend web_servers\n"
var2="\nbackend web_servers\n\tbalance roundrobin\n\tserver 1036-web-01 35.196.120.179:80 cookie 1036-web-01\n\tserver 1036-web-02 35.229.21.132:80 cookie 1036-web-02\n"
sudo sed -i "35a \ $var1 $var2" /etc/haproxy/haproxy.cfg
