#!/usr/bin/env bash
# Generated a MySQL dump and creates a compressed archive out of it
sudo mysqldump -u root -p $1 --all-databases > backup.sql
sudo mysqldump -u root -p $1 --all-databases | gzip > $(date +'%d-%m-%Y').tar.gz
