#!/usr/bin/env bash
# Copy previous task and service (init) must say that nginx is not running ← for real
sudo sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
sudo service nginx restart
> /var/run/nginx.pid
