#!/usr/bin/env bash
# Gives information about the holbertonschool file
FILE=holbertonschool
if test -e $FILE; then
	echo "holbertonschool file exists"
else
	echo "holbertonschool file does not exist"
fi

if [ -s $FILE]; then
	echo "holbertonschool file is not empty"
else
	echo "holbertonschool file is empty"
fi

if test -f $FILE; then
	echo "holbertonschool is a regular file"
fi
