#!/usr/bin/env bash
# Make nginx be running as the nginx user, and change all active IPs on port 8080
sudo apt-get -y update
sudo apt-get -y install nginx
sudo apt-install 
sudo -u nginx nginx
sudo sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
sudo service nginx start
