#!/usr/bin/env bash
# Make nginx be running as the nginx user, and change all active IPs on port 8080
sudo -u nginx nginx
sudo sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
sudo service nginx restart
