#!/usr/bin/env bash
# Make nginx be running as the nginx user, and change all active IPs on port 8080
chmod 777 /etc/nginx/nginx.conf
sudo -u nginx nginx
sudo sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
sudo service nginx start
